/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint32_t deneme_bss_1[100] = {0}  ;
volatile uint32_t deneme_bss_2[100] = {0} ;
volatile uint32_t deneme_data[100] = {0x20, 0x50, 0x50, 0x200};


int main(void)
{
    /* Loop forever */
	for(;;)
	{
		deneme_data[10]= deneme_bss_1[10];
		deneme_bss_1[99]= 0x300;
		deneme_bss_2[99]= 0x100;
	}
}
